release:
  prerelease: auto
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./oomcli
    id: "oomcli"
    binary: oomcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - >
        -s -w
        -X github.com/oom-ai/oomstore/version.Version={{.Version}}
        -X github.com/oom-ai/oomstore/version.Commit={{.Commit}}
        -X github.com/oom-ai/oomstore/version.Built={{.CommitDate}}
  - main: ./oomagent
    id: "oomagent"
    binary: oomagent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - >
        -s -w
        -X github.com/oom-ai/oomstore/version.Version={{.Version}}
        -X github.com/oom-ai/oomstore/version.Commit={{.Commit}}
        -X github.com/oom-ai/oomstore/version.Built={{.CommitDate}}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge"
      - "^Update"
      - "^docs[:(]"
      - "^test[:(]"
      - "^chore[:(]"
      - "^refactor[:(]"
      - "^ci[:(]"
